version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/RandoSettingsManagerService"
    schedule:
      interval: "weekly"
    groups:
      lambda:
        patterns:
          - "Amazon.Lambda.*"
      aws-sdk:
        patterns:
          - "AWSSDK.*"
  - package-ecosystem: "nuget"
    directory: "/RandoSettingsManagerServiceCDK"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
