version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/RandoSettingsManagerService"
    schedule:
      interval: "weekly"
    groups:
      Lambda:
        applies-to: all
        patterns:
          - "Amazon.Lambda.*"
      AWSSDK:
        applies-to: all
        patterns:
          - "AWSSDK.*"
  - package-ecosystem: "nuget"
    directory: "/RandoSettingsManagerServiceCDK"
    schedule:
      interval: "weekly"
    groups:
      Dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
